#!/usr/bin/env bash

clear

set -euo pipefail

[[ -f /etc/os-release ]] && . /etc/os-release

if [[ $ID != "arch" ]]; then
	echo "OS not detected as archlinux"
	exit 1
fi

sudo -v
timestamp_sudo() {
	while :; do
		sudo -v
		sleep 45
	done
}
timestamp_sudo &
timestamp_sudo_pid=$!
trap "sudo -k; kill -9 $timestamp_sudo_pid 2>/dev/null;" EXIT SIGINT SIGTERM

source ./peripheral/networking
source ./peripheral/bluetooth
source ./peripheral/pipewire
source ./peripheral/graphic
source ./peripheral/disk
source ./peripheral/battery

source ./desktop/dotfiles
source ./desktop/common
source ./desktop/wm
source ./desktop/zen-browser
source ./desktop/ime
source ./desktop/udiskie
source ./desktop/nerdfonts
source ./desktop/theme
source ./desktop/sddm

source ./dev/nodejs
source ./dev/golang
source ./dev/php
source ./dev/rust
source ./dev/neovim
source ./dev/git

clear
echo "Success, need reboot"
