#!/usr/bin/env bash

packages=(
	docker
	docker-compose
	docker-buildx
)

sudo pacman -S --noconfirm --needed "${packages[@]}"

if ! getent group docker; then
	sudo groupadd docker
fi
sudo usermod -aG docker "$USER"
sudo systemctl enable docker
