#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed wget tar

version=1.24.1

wget -N -O /tmp/go"$version".linux-amd64.tar.gz https://go.dev/dl/go"$version".linux-amd64.tar.gz

sudo rm -rf /usr/local/go
sudo tar -C /usr/local/ -xzf /tmp/go"$version".linux-amd64.tar.gz
