#!/usr/bin/env bash

clear

sudo pacman -S --noconfirm --needed wget tar

VERSION=1.24.1
DOWNLOAD_NAME=go"$VERSION".linux-amd64.tar.gz

if ! tar -tvf /tmp/"$DOWNLOAD_NAME" &>/dev/null; then
	curl -Lo /tmp/"$DOWNLOAD_NAME" https://go.dev/dl/"$DOWNLOAD_NAME"
fi

if ! [[ -e "$HOME/$shellrc" ]]; then
	touch "$HOME/$shellrc"
fi

if ! grep -i "# Golang" "$HOME/$shellrc" &>/dev/null; then
	tee -a "$HOME/$shellrc" <<-EOF
		# Golang
		export PATH="/usr/local/go/bin:\$PATH"
		export PATH="\$HOME/go/bin:\$PATH"
	EOF
fi
