#!/usr/bin/env bash

clear

if [[ "${GLOBAL:-}" != 1 ]]; then
	source ./dev/nodejs
	source ./dev/golang
	source ./dev/php
	source ./dev/rust
fi

current_dir=$PWD

packages=(
	git
	base-devel
	make
	cmake
	ninja
	gettext
	luarocks
	tree-sitter-cli
	curl
	wget
	unzip
	tar
	gzip
)

sudo pacman -S --noconfirm --needed "${packages[@]}"

version=v0.11.2
if ! [[ -d /tmp/neovim ]]; then
	git clone --depth 1 -b "$version" https://github.com/neovim/neovim /tmp/neovim
fi

cd /tmp/neovim
make deps
make CMAKE_BUILD_TYPE=Release -j"$(nproc 2>/dev/null || getconf _NPROCESSORS_CONF)"
sudo make install

if ! [[ -d $HOME/.config/nvim ]]; then
	git clone https://github.com/akbarsanihasan/nvimrc.git "$HOME"/.config/nvim
fi

cd "$current_dir"
