#!/usr/bin/env bash

export NPM_CONFIG_CACHE=$HOME/.node
export NPM_CONFIG_PREFIX=$HOME/.node

sudo pacman -S --noconfirm --needed curl unzip

if ! command -v fnm &>/dev/null; then
	curl -fsSL https://fnm.vercel.app/install |
		sudo bash -s -- --skip-shell --install-dir /usr/local/bin
fi

eval "$(fnm env --fnm-dir "$HOME"/.node)"
fnm install --lts
