#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed curl

curl -fsSL https://php.new/install/linux | bash

sudo rm -rf /usr/local/php
sudo mv "$HOME"/.config/herd-lite/ /usr/local/php
sudo mv /usr/local/php/bin/cacert.pem /usr/local/php
sudo rm -rf /usr/local/php/bin/php.ini

if ! [[ -f /usr/local/php/php.ini ]]; then
	tee /usr/local/php/php.ini <<-EOF
		curl.cainfo=/usr/local/php/bin/cacert.pem
		openssl.cafile=/usr/local/php/bin/cacert.pem
		pcre.jit=0
	EOF
fi
