#!/usr/bin/env bash

set -euo pipefail

sudo pacman -S --noconfirm --needed git

if command -v flatpak &>/dev/null; then
    flatpak install --user --noninteractive --assumeyes com.calibre_ebook.calibre
    flatpak override --user --filesystem=home com.calibre_ebook.calibre
    flatpak override --user --filesystem=host com.calibre_ebook.calibre
    flatpak override --user --filesystem=host-os com.calibre_ebook.calibre
    flatpak override --user --filesystem=xdg-config/calibre com.calibre_ebook.calibre
fi

mkdir "$HOME"/.config/calibre
if ! [[ -d $HOME/Books ]]; then
    git clone https://github.com/akbarsanihasan/Books.git "$HOME"/Books
fi
