#!/usr/bin/env bash

if command -v flatpak &>/dev/null; then
    echo -e "Flatpak is not installed"

    flatpak install --user --noninteractive --assumeyes md.obsidian.Obsidian
    flatpak override --user --socket=wayland md.obsidian.Obsidian
    flatpak override --user --socket=system-bus md.obsidian.Obsidian
    flatpak override --user --filesystem=home md.obsidian.Obsidian
    flatpak override --user --filesystem=home/Notes md.obsidian.Obsidian
    flatpak override --user --filesystem=host md.obsidian.Obsidian
    flatpak override --user --filesystem=host-os md.obsidian.Obsidian
fi

if ! [[ -d "$HOME"/Notes ]]; then
    git clone https://github.com/akbarsanihasan/Notes "$HOME"/Notes
fi
