#!/usr/bin/env bash
sudo pacman -S --noconfirm --needed tlp

sudo mkdir -p /etc/tlp.d

sudo tee /etc/tlp.d/10-threshold.conf <<-EOF
	START_CHARGE_THRESH_BAT0=75
	STOP_CHARGE_THRESH_BAT0=80
	START_CHARGE_THRESH_BAT1=75
	STOP_CHARGE_THRESH_BAT1=80
	RESTORE_THRESHOLDS_ON_BAT=1
EOF

sudo systemctl enable tlp
