#!/usr/bin/env bash

sudo pacman -S --needed --noconfirm util-linux exfatprogs ntfs-3g

while read gran; do
	if [[ $gran -gt 0 ]] && ! sudo systemctl --quiet is-enabled fstrim.timer; then
		sudo systemctl enable fstrim.timer
		sudo systemctl start fstrim.timer
		break
	fi
done < <(lsblk -p -d --discard --noheadings --bytes -o 'DISC-GRAN')
