#!/usr/bin/env bash

if systemctl --quiet is-active NetworkManager-wait-online; then
	sudo systemctl stop NetworkManager-wait-online.service
	sudo systemctl disable NetworkManager-wait-online.service
	sudo systemctl mask NetworkManager-wait-online.service
fi
