#!/usr/bin/env bash

sudo pacman -S --needed --noconfirm util-linux exfatprogs ntfs-3g

while read disk; do
	disc_gran=$(lsblk -p -d --discard --noheadings --bytes -o 'DISC-GRAN' "$disk")

	if [[ $disc_gran -gt 0 ]]; then
		if ! sudo --quiet systemctl is-active fstrim.timer; then
			sudo systemctl enable fstrim.timer
			sudo systemctl start fstrim.timer
			break
		fi
	fi
done < <(lsblk --noheadings -p -d -o name)
