#!/usr/bin/env bash

clear

sudo pacman -S --noconfirm --needed wget tar

VERSION=1.24.1
DOWNLOAD_PATH=$HOME/.cache/dotfiles/go"$VERSION".linux-amd64.tar.gz
INSTALL_PATH=/opt/go

if ! tar -tvf "$DOWNLOAD_PATH" &>/dev/null; then
	curl -Lo "$DOWNLOAD_PATH" https://go.dev/dl/"$(basename "$DOWNLOAD_PATH")"
fi

sudo rm -rf /"$INSTALL_PATH"
sudo tar -C "$(dirname "$INSTALL_PATH")" -xzf "$DOWNLOAD_PATH"

shellrcs=(.zshrc .bashrc)
for shellrc in "${shellrcs[@]}"; do
	if ! [[ -e "$HOME/$shellrc" ]]; then
		touch "$HOME/$shellrc"
	fi
	if ! grep -i "# Golang" "$HOME/$shellrc" &>/dev/null; then
		tee -a "$HOME/$shellrc" <<-EOF
			# Golang
			export PATH="$INSTALL_PATH/bin:\$PATH"
			export PATH="\$HOME/go/bin:\$PATH"
		EOF
	fi
done
