#!/usr/bin/env bash

clear

current_dir=$PWD

URL="https://code.visualstudio.com/sha/download?build=stable&os=linux-x64"
DOWNLOAD_PATH=$HOME/.cache/dotfiles/vscode.tar.gz
INSTALL_PATH=/opt/vscode

if ! tar -tvf "$DOWNLOAD_PATH" &>/dev/null; then
    curl -Lo "$DOWNLOAD_PATH" "$URL"
fi

sudo rm -rf "$INSTALL_PATH"
sudo mkdir -p "$INSTALL_PATH"
sudo tar --strip-components=1 -C "$INSTALL_PATH" -xvf "$DOWNLOAD_PATH"

sudo tee /usr/local/bin/code <<-EOF
	exec $INSTALL_PATH/bin/code \${@}
EOF
sudo chmod +x /usr/local/bin/code

sudo tee /usr/local/share/applications/code.desktop <<-EOF
	[Desktop Entry]
	Name=Visual Studio Code
	Comment=Programming Text Editor
	Exec=/usr/local/bin/code
	Icon=$INSTALL_PATH/resources/app/resources/linux/code.png
	Terminal=false
	Type=Application
	Categories=Programming
EOF
