#!/usr/bin/env bash

sudo pacman -S --noconfirm gnupg

trap 'unset GIT_TOKEN' EXIT SIGINT SIGTERM

GIT_USER=akbarsanihasan
GIT_TOKEN=$(gpg --decrypt --quiet "$PWD"/secrets.asc)

if [[ -z $GIT_TOKEN ]]; then
	exit 1
fi
