#!/usr/bin/env bash

if [[ "${GLOBAL:-}" != 1 ]]; then
	source ./Shared/secrets
	source ./Shared/install_dotfiles
fi

packages=(
	git
	zsh
	foot
	mpv
	tmux
	fzf
	btop
	bat
	eza
	fastfetch
	trash-cli
	man
	tldr
)

tools=(
	fd
	jq
	ripgrep
	gawk
	less
	curl
	wget
	tar
	zip
	unzip
	unrar
	p7zip
)

sudo pacman -S --noconfirm --needed "${packages[@]}" "${tools[@]}"

if ! [[ -d $HOME/.common ]]; then
	git clone https://"$GIT_TOKEN"@github.com/"$GIT_USER"/dotfiles-common "$HOME"/.common
fi

if ! [[ -e "$HOME"/.config/tmux/plugins/tpm ]]; then
	git clone https://github.com/tmux-plugins/tpm "$HOME"/.config/tmux/plugins/tpm
fi

install_dotfile .common

"$HOME"/.config/tmux/plugins/tpm/bin/install_plugins all
sudo chsh -s "$(command -v zsh)" "$USER"
zsh -c "source $HOME/.zshrc" || true
bat cache --build
