#!/usr/bin/env bash

clear

export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}

current_dir=$PWD

dependencies=(
    bash
    cairo
    flex
    freetype2
    gdk-pixbuf2
    hicolor-icon-theme
    libjpeg
    librsvg
    libx11
    libxcb
    libxdg-basedir
    libxft
    libxkbcommon
    libxkbcommon-x11
    pango
    startup-notification
    xcb-imdkit
    xcb-util
    xcb-util-cursor
    xcb-util-keysyms
    xcb-util-wm
    xcb-util-xrm
    libqalculate
    noto-fonts-emoji
)

build_dependencies=(
    git
    base-devel
    wayland-protocols
    meson
    make
    glib2
    glibc
    check
    autoconf
    automake
    libtool
)

sudo pacman -S --noconfirm --needed "${dependencies[@]}" "${build_dependencies[@]}"

REPOS=(davatorium/rofi svenstaro/rofi-calc mange/rofi-emoji)
REPO_VERSIONS=(1.7.9.1 v2.3.2 v4.1.0)

for i in "${!REPOS[@]}"; do
    REPO=${REPOS[$i]}
    DOWNLOAD_PATH=/tmp/$(basename "$REPO")

    if ! [[ -d $DOWNLOAD_PATH ]]; then
        git clone --recursive --depth 1 -b "${REPO_VERSIONS[$i]}" https://github.com/"$REPO" "$DOWNLOAD_PATH"
    fi

    cd "$DOWNLOAD_PATH"
    if [[ $(basename "$REPO") == "rofi-emoji" ]]; then
        autoreconf -i
        ./configure --prefix=/usr/local
        make
        sudo make install
        continue
    fi
    meson setup ./build --reconfigure \
        --prefix=/usr/local \
        --sysconfdir=/etc
    meson compile -C ./build
    sudo meson install -C ./build
done

cd "$current_dir"
