#!/usr/bin/env bash

clear

sudo pacman -S --noconfirm git base-devel

AURH=yay

if ! [[ -d /tmp/$AURH ]]; then
	git clone https://aur.archlinux.org/"$AURH"-bin.git /tmp/"$AURH"
fi

cd /tmp/"$AURH"
makepkg -sri --noconfirm
