#!/usr/bin/env bash

clear

DOWNLOAD_PATH=/tmp/vscode.tar.gz
INSTALL_PATH=/opt/vscode
URL="https://code.visualstudio.com/sha/download?build=stable&os=linux-x64"
if ! tar -tvf "$DOWNLOAD_PATH" &>/dev/null; then
	curl -Lo "$DOWNLOAD_PATH" "$URL"
fi

sudo rm -rf "$INSTALL_PATH"
sudo mkdir -p "$INSTALL_PATH"
sudo tar --strip-components=1 -C "$INSTALL_PATH" -xvf "$DOWNLOAD_PATH"
sudo chown -R "$USER" "$INSTALL_PATH"

tee "$HOME"/.local/bin/code <<-EOF
	#/usr/bin/env bash
	exec $INSTALL_PATH/bin/code \${@}
EOF
chmod +x "$HOME"/.local/bin/code

mkdir -p "$HOME"/.local/share/applications
tee "$HOME"/.local/share/applications/code.desktop <<-EOF
	[Desktop Entry]
	Name=Visual Studio Code
	Comment=Programming Text Editor
	Exec=/usr/local/bin/code
	Icon=$INSTALL_PATH/resources/app/resources/linux/code.png
	Terminal=false
	Type=Application
	Categories=Programming
EOF
