#!/usr/bin/env bash

clear

mkdir -p "$HOME"/.cache/dotfiles

sudo pacman -S --noconfirm --needed curl \
	tar \
	firefox \
	chromium

INSTALL_PATH=/opt/zen
DOWNLOAD_PATH=$HOME/.cache/dotfiles/zen.linux-x86_64.tar.xz

if ! tar -tvf "$DOWNLOAD_PATH" &>/dev/null; then
	curl -Lo "$DOWNLOAD_PATH" https://github.com/zen-browser/desktop/releases/latest/download/"$(basename "$DOWNLOAD_PATH")"
fi

sudo rm -rf "$INSTALL_PATH"
sudo tar -C /opt/ -xvf "$DOWNLOAD_PATH"

sudo tee /usr/local/share/applications/zen.desktop <<-EOF
	[Desktop Entry]
	Name=Zen Browser
	Comment=Experience tranquillity while browsing the web without people tracking you!
	Keywords=web;browser;internet
	Exec=$INSTALL_PATH/zen %u
	Icon=$INSTALL_PATH/browser/chrome/icons/default/default128.png
	Terminal=false
	StartupNotify=true
	StartupWMClass=zen
	NoDisplay=false
	Type=Application
	MimeType=text/html;text/xml;application/xhtml+xml;application/vnd.mozilla.xul+xml;text/mml;x-scheme-handler/http;x-scheme-handler/https;
	Categories=Network;WebBrowser;
	Actions=new-window;new-private-window;profile-manager-window;
	[Desktop Action new-window]
	Name=Open a New Window
	Exec=$INSTALL_PATH/zen --new-window %u
	[Desktop Action new-private-window]
	Name=Open a New Private Window
	Exec=$INSTALL_PATH/zen --private-window %u
	[Desktop Action profile-manager-window]
	Name=Open the Profile Manager
	Exec=$INSTALL_PATH/zen --ProfileManager
EOF
