#!/usr/bin/env bash

if [[ "${GLOBAL:-}" != 1 ]]; then
	source ./desktop/flatpak
fi

sudo pacman -S --noconfirm --needed xdg-utils

apps=(
	app.zen_browser.zen
	org.mozilla.firefox
	org.chromium.Chromium
)

for app in "${apps[@]}"; do
	flatpak install \
		--user \
		--noninteractive \
		--assumeyes \
		"$app"
done

flatpak override --user "${zen_browser_override[@]}" app.zen_browser.zen
flatpak override --user "${firefox_override[@]}" org.mozilla.firefox

if ! [[ "$(xdg-settings get default-web-browser)" == "app.zen_browser.zen.desktop" ]]; then
	xdg-settings set default-web-browser app.zen_browser.zen.desktop
fi
