#!/usr/bin/env bash

clear

common=(tmux zsh fzf btop trash-cli)
compositor=(wayland xorg-xwayland sway swayidle swaybg swaylock xdg-desktop-portal xdg-desktop-portal-wlr xdg-desktop-portal-gtk)
widgets=(waybar swaync rofi rofi-calc rofi-emoji)
utilities=(wl-clipboard cliphist grim polkit-gnome libnotify brightnessctl playerctl pavucontrol blueman nm-connection-editor)
apps=(foot mpv chromium firefox thunar file-roller okular ristretto mousepad flameshot)
lib=(xdg-user-dirs gvfs gvfs-mtp thunar-archive-plugin thunar-volman thunar-media-tags-plugin tumbler ffmpegthumbnailer webp-pixbuf-loader imagemagick)
tools=(coreutils git dconf fd jq ripgrep gawk less curl wget tar zip unzip unrar p7zip man tldr)

sudo pacman -S --noconfirm --needed "${common[@]}" \
	"${compositor[@]}" \
	"${widgets[@]}" \
	"${apps[@]}" \
	"${utilities[@]}" \
	"${lib[@]}" \
	"${tools[@]}"

sudo chsh -s "$(command -v zsh)" "$USER"

dconf write /org/blueman/general/plugin-list "['!ShowConnected', '!StatusIcon']"
dconf write /org/gnome/desktop/wm/preferences/button-layout "':'"

/usr/bin/xdg-user-dirs-update
mkdir -p "$HOME"/.config/gtk-3.0
tee "$HOME"/.config/gtk-3.0/bookmarks <<-EOF
	file:///home/$USER/Documents
	file:///home/$USER/Downloads
	file:///home/$USER/Music
	file:///home/$USER/Pictures
	file:///home/$USER/Public
	file:///home/$USER/Templates
	file:///home/$USER/Videos
EOF
