#!/usr/bin/env bash

if [[ "${GLOBAL:-}" != 1 ]]; then
	source ./desktop/flatpak
fi

sudo pacman -S --noconfirm --needed grim
flatpak install --user --noninteractive --assumeyes org.flameshot.Flameshot
flatpak override --user --filesystem=xdg-config/flameshot org.flameshot.Flameshot

mkdir -p "$HOME"/Pictures/Screenshot
mkdir -p "$HOME"/.config/flameshot

tee "$HOME"/.config/flameshot/flameshot.ini <<-EOF
	[General]
	drawFontSize=9
	saveLastRegion=true
	savappHOME/Pictures/Screenshot
	savePathFixed=false
	saveAsFileExtension=png
	showHelp=false
	startupLaunch=true
	showStartupLaunchMessage=false
	showDesktopNotification=false
EOF
