#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed flatpak

flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo

flatpak override --user --allow=bluetooth

flatpak override --user --device=dri
flatpak override --user --device=shm
flatpak override --user --device=all

flatpak override --user --socket=x11
flatpak override --user --socket=wayland
flatpak override --user --socket=pulseaudio
flatpak override --user --socket=session-bus
flatpak override --user --socket=system-bus
flatpak override --user --socket=ssh-auth

flatpak override --user --filesystem=home
flatpak override --user --filesystem=xdg-config/gtk-3.0:ro
flatpak override --user --filesystem=xdg-config/gtk-4.0:ro
flatpak override --user --filesystem=xdg-config/Kvantum:ro
flatpak override --user --filesystem=xdg-data/themes:ro
flatpak override --user --filesystem=xdg-data/fonts:ro

flatpak override --user --env=QT_QPA_PLATFORM="wayland;xcb"
flatpak override --user --env=ELECTRON_OZONE_PLATFORM_HINT=auto

apps=(
	app.zen_browser.zen
	org.mozilla.firefox
	org.chromium.Chromium
	md.obsidian.Obsidian
	org.onlyoffice.desktopeditors
	com.calibre_ebook.calibre
	com.github.tchx84.Flatseal
)

for app in "${apps[@]}"; do
	flatpak install --user --noninteractive --assumeyes --app "$app"
done
