#!/usr/bin/env bash

if [[ "${GLOBAL:-}" != 1 ]]; then
	source ./Shared/secrets
	source ./Shared/dotfiles
	source ./desktop/flatpak
fi

sudo pacman -S --noconfirm --needed git

apps=(
	app.zen_browser.zen
	org.mozilla.firefox
	org.chromium.Chromium
	md.obsidian.Obsidian
	com.calibre_ebook.calibre
)

personal_repos=(Personal setup-extras)
personal_repos_dest=("$PWD"/.personal "$PWD"/Extras)

for repo_index in ${!personal_repos[@]}; do
	if ! [[ -d "${personal_repos_dest[$repo_index]}" ]]; then
		git clone --depth 1 \
			https://"$GIT_TOKEN"@github.com/"$GIT_USER"/"${personal_repos[$repo_index]}".git \
			"${personal_repos_dest[$repo_index]}"
	fi
done

install_dotfile "$PWD"/.personal

for app_id in "${!apps[@]}"; do
	flatpak install \
		--user \
		--noninteractive \
		--assumeyes \
		"${apps[$app_id]}"
done

# Calibre reader
calibre_override=(
	--filesystem=xdg-config/calibre
)
flatpak override --user --filesystem=xdg-config/calibre com.calibre_ebook.calibre

if ! grep -ie "\"database_path\":.*$HOME/.*" "$HOME"/.config/calibre/global.py.json; then
	sed -i --follow-symlinks "s|\"database_path\": *\"[^\"]*\"|\"database_path\": \"$HOME/library1.db\"|" "$HOME/.config/calibre/global.py.json"
fi
if ! grep -ie "\"library_path\":.*$HOME/.*" "$HOME"/.config/calibre/global.py.json; then
	sed -i --follow-symlinks "s|\"library_path\": *\"[^\"]*\"|\"library_path\": \"$HOME/Calibre Library\"|" "$HOME/.config/calibre/global.py.json"
fi
