#!/usr/bin/env bash

if [[ "${GLOBAL:-}" != 1 ]]; then
	source ./Shared/secrets
	source ./Shared/dotfiles
fi

sudo pacman -S --noconfirm --needed git

personal_repos=(Personal setup-extras)
personal_repos_dest=("$PWD"/.personal "$PWD"/extras)

for repo_index in ${!personal_repos[@]}; do
	if ! [[ -d "${personal_repos_dest[$repo_index]}" ]]; then
		git clone --depth 1 \
			https://"$GIT_TOKEN"@github.com/"$GIT_USER"/"${personal_repos[$repo_index]}".git \
			"${personal_repos_dest[$repo_index]}"
	fi
done

install_dotfile "$PWD"/.personal
if ! grep -ie "\"library_path\":.*$HOME/Books" "$HOME"/.config/calibre/global.py.json; then
	sed -i --follow-symlinks "s|\"library_path\": *\"[^\"]*\"|\"library_path\": \"$HOME/Books\"|" "$HOME/.config/calibre/global.py.json"
fi
if ! grep -ie "\"database_path\":.*$HOME/Books/library1.db" "$HOME"/.config/calibre/global.py.json; then
	sed -i --follow-symlinks "s|\"database_path\": *\"[^\"]*\"|\"database_path\": \"$HOME/Books/library1.db\"|" "$HOME/.config/calibre/global.py.json"
fi
