#!/usr/bin/env bash

if [[ "${GLOBAL:-}" != 1 ]]; then
	source ./Shared/secrets
	source ./Shared/dotfiles
	source ./hardware/network
	source ./hardware/pipewire
	source ./hardware/bluetooth
fi

core=(
	git
	make
	zsh
	wayland
	xorg-xwayland

	sway
	swayidle
	swaylock
	swaybg
	xdg-desktop-portal-wlr
	xdg-desktop-portal-gtk
	xdg-desktop-portal-kde

	wl-clipboard
	cliphist
	polkit-kde-agent
	libnotify
	brightnessctl
	playerctl
	xdg-user-dirs
)

companion=(
	waybar
	swaync
	rofi-wayland
	rofi-calc
	rofi-emoji
	noto-fonts-emoji

	thunar
	gvfs
	file-roller
	okular
	ristretto
	mousepad
	pavucontrol
	blueberry
	nm-connection-editor
)

tools=(
	fd
	jq
	ripgrep
	gawk
	less
	curl
	wget
	tar
	zip
	unzip
	unrar
	p7zip
)

sudo pacman -S --noconfirm --needed \
	"${core[@]}" \
	"${companion[@]}" \
	"${tools[@]}"

if ! [[ -d $PWD/.swaywm ]]; then
	git clone https://"$GIT_TOKEN"@github.com/"$GIT_USER"/dotfiles-swaywm "$PWD"/.swaywm
fi
if ! [[ -d $HOME/.wallpapers ]]; then
	git clone https://"$GIT_TOKEN"@github.com/"$GIT_USER"/wallpapers "$HOME"/.wallpapers
fi
install_dotfile "$PWD"/.swaywm

sudo chsh -s "$(command -v zsh)" "$USER"
sudo usermod -aG input "$USER"

/usr/bin/xdg-user-dirs-update

mkdir -p "$HOME"/.config/gtk-3.0/
tee "$HOME"/.config/gtk-3.0/bookmarks <<-EOF
	file:///home/$USER/Documents
	file:///home/$USER/Downloads
	file:///home/$USER/Music
	file:///home/$USER/Pictures
	file:///home/$USER/Public
	file:///home/$USER/Templates
	file:///home/$USER/Videos
EOF
