#!/usr/bin/env bash

clear

current_dir=$PWD

fonts=(inter-font ttf-dejavu ttf-liberation noto-fonts-emoji)
theme=(nwg-look kvantum sassc qt5ct qt5-wayland qt6ct qt6-wayland adwaita-cursors dconf)

sudo pacman -S --noconfirm "${fonts[@]}" "${theme[@]}"

mkdir -p "$current_dir"/.cache
REPOS=(vinceliuice/Colloid-gtk-theme PapirusDevelopmentTeam/papirus-icon-theme catppuccin/qt5ct)
VERSIONS=(2024-11-16 20250201 main)
DOWNLOAD_PATH=(gtk-theme icon-pack qtnct)

for i in "${!REPOS[@]}"; do
    if ! [[ -d "$current_dir/.cache/${DOWNLOAD_PATH[$i]}" ]]; then
        git clone --depth 1 -b "${VERSIONS[$i]}" https://github.com/"${REPOS[$i]}" "$current_dir/.cache/${DOWNLOAD_PATH[$i]}"
    fi
done

mkdir -p "$HOME"/.local/share/themes
sed -E -i '/^\$(modal|corner|menu|window)-radius:/s/:[^;]+;/\: 0px;/' "$current_dir"/.cache/gtk-theme/src/sass/_variables.scss
cd "$current_dir"/.cache/gtk-theme
./install.sh --dest "$HOME"/.local/share/themes \
    --theme default \
    --color dark \
    --size compact \
    --libadwaita system \
    --tweaks catppuccin black rimless

cd "$current_dir"/.cache/icon-pack
make install PREFIX="$HOME"/.local

mkdir -p "$HOME"/.config/{qt5ct,qt6ct}/colors/
cp "$current_dir"/.cache/qtnct/themes/catppuccin-mocha-blue.conf "$HOME"/.config/qt5ct/colors/catppuccin-mocha.conf

dconf write /org/gnome/desktop/interface/cursor-theme "'Adwaita'"
dconf write /org/gnome/desktop/interface/font-name "'Inter Display Semi-Bold 14'"
dconf write /org/gnome/desktop/interface/gtk-theme "'Colloid-Dark-Compact-Catppuccin'"
dconf write /org/gnome/desktop/wm/preferences/theme "'Colloid-Dark-Compact-Catppuccin'"
dconf write /org/gnome/desktop/interface/color-scheme "'prefer-dark'"
dconf write /org/gnome/desktop/interface/icon-theme "'Papirus-Dark'"

cd "$current_dir"
