#!/usr/bin/env bash

clear

current_dir=$PWD

fonts=(inter-font ttf-dejavu ttf-liberation noto-fonts-emoji)
theme=(make dconf sassc nwg-look kvantum-qt5 qt5-wayland adwaita-cursors)

sudo pacman -S --noconfirm "${fonts[@]}" "${theme[@]}"

fc-cache -vf

REPOS=(vinceliuice/Colloid-gtk-theme PapirusDevelopmentTeam/papirus-icon-theme catppuccin/qt5ct)
VERSIONS=(2024-11-16 20250201 main)
DOWNLOAD_PATH=(gtk-theme icon-pack qtnct)

for i in "${!REPOS[@]}"; do
	if ! [[ -d /tmp/"${DOWNLOAD_PATH[$i]}" ]]; then
		git clone --depth 1 -b "${VERSIONS[$i]}" https://github.com/"${REPOS[$i]}" /tmp/"${DOWNLOAD_PATH[$i]}"
	fi
done

sed -E -i '/^\$(modal|corner|menu|window)-radius:/s/:[^;]+;/\: 0px;/' /tmp/gtk-theme/src/sass/_variables.scss

mkdir -p "$HOME"/.local/share/themes
cd /tmp/gtk-theme
./install.sh --dest "$HOME"/.local/share/themes \
	--theme default \
	--color dark \
	--size compact \
	--libadwaita system \
	--tweaks catppuccin black rimless

cd /tmp/icon-pack
make install PREFIX="$HOME"/.local

dconf write /org/gnome/desktop/interface/cursor-theme "'Adwaita'"
dconf write /org/gnome/desktop/interface/font-name "'Inter Display 14'"
dconf write /org/gnome/desktop/interface/gtk-theme "'Colloid-Dark-Compact-Catppuccin'"
dconf write /org/gnome/desktop/wm/preferences/theme "'Colloid-Dark-Compact-Catppuccin'"
dconf write /org/gnome/desktop/interface/color-scheme "'prefer-dark'"
dconf write /org/gnome/desktop/interface/icon-theme "'Papirus-Dark'"

cd "$current_dir"
