#!/usr/bin/env bash

clear

current_dir=$PWD

fonts=(inter-font ttf-dejavu ttf-liberation noto-fonts-emoji)
theme=(nwg-look kvantum sassc qt5ct qt5-wayland qt6ct qt6-wayland adwaita-cursors dconf)

sudo pacman -S --noconfirm "${fonts[@]}" "${theme[@]}"

if ! [[ -d $HOME/.cache/dotfiles/gtk-theme ]]; then
	git clone --depth 1 -b 2024-11-16 https://github.com/vinceliuice/Colloid-gtk-theme "$HOME"/.cache/dotfiles/gtk-theme
	sed -E -i '/^\$(modal|corner|menu|window)-radius:/s/:[^;]+;/\: 0px;/' "$HOME"/.cache/dotfiles/gtk-theme/src/sass/_variables.scss
fi
if ! [[ -d $HOME/.cache/dotfiles/icon-pack ]]; then
	git clone --depth 1 -b 20250201 https://github.com/PapirusDevelopmentTeam/papirus-icon-theme "$HOME"/.cache/dotfiles/icon-pack
fi
if [[ -d "$HOME"/.local/share/themes ]]; then
	mkdir -p "$HOME"/.local/share/themes
fi

cd "$HOME"/.cache/dotfiles/gtk-theme
./install.sh --dest "$HOME"/.local/share/themes \
	--theme default \
	--color dark \
	--size compact \
	--libadwaita system \
	--tweaks catppuccin black rimless
cd "$HOME"/.cache/dotfiles/icon-pack
make install PREFIX="$HOME"/.local

if ! [[ -d $HOME/.cache/dotfiles/qtnct ]]; then
	git clone --depth 1 https://github.com/catppuccin/qt5ct "$HOME"/.cache/dotfiles/qtnct
fi
mkdir -p "$HOME"/.config/{qt5ct,qt6ct}/colors/
cp "$HOME"/.cache/dotfiles/qtnct/themes/catppuccin-mocha-blue.conf "$HOME"/.config/qt5ct/colors/catppuccin-mocha.conf

dconf write /org/gnome/desktop/interface/cursor-theme "'Adwaita'"
dconf write /org/gnome/desktop/interface/font-name "'Inter Display Semi-Bold 14'"
dconf write /org/gnome/desktop/interface/gtk-theme "'Colloid-Dark-Compact-Catppuccin'"
dconf write /org/gnome/desktop/wm/preferences/theme "'Colloid-Dark-Compact-Catppuccin'"
dconf write /org/gnome/desktop/interface/color-scheme "'prefer-dark'"
dconf write /org/gnome/desktop/interface/icon-theme "'Papirus-Dark'"

cd "$current_dir"
