#!/usr/bin/env bash

clear

wm=(
    wayland
    xorg-xwayland
    sway
    swayidle
    swaybg
    swaylock
    xdg-desktop-portal
    xdg-desktop-portal-wlr
    xdg-desktop-portal-gtk
)
utilities=(
    dconf
    xdg-user-dirs
    wl-clipboard
    grim
    gvfs
    polkit-gnome
    libnotify
    brightnessctl
    playerctl
)
panels=(
    waybar
    dunst
    rofi
    pavucontrol
    blueman
    nm-connection-editor
)
dependencies=(
    rofi-calc
    rofi-emoji
    cliphist
)

sudo pacman -S --noconfirm --needed "${wm[@]}" \
    "${utilities[@]}" \
    "${panels[@]}" \
    "${apps[@]}" \
    "${dependencies[@]}"

dconf write /org/blueman/general/plugin-list "['!ShowConnected', '!StatusIcon']"
dconf write /org/gnome/desktop/wm/preferences/button-layout "':'"

/usr/bin/xdg-user-dirs-update
mkdir -p "$HOME"/.config/gtk-3.0
tee "$HOME"/.config/gtk-3.0/bookmarks <<-EOF
	file:///home/$USER/Documents
	file:///home/$USER/Downloads
	file:///home/$USER/Music
	file:///home/$USER/Pictures
	file:///home/$USER/Public
	file:///home/$USER/Templates
	file:///home/$USER/Videos
EOF
