#!/usr/bin/env bash

clear

sudo pacman -S --noconfirm --needed curl tar

INSTALL_PATH=/opt/zen
DOWNLOAD_PATH=/tmp/zen.linux-x86_64.tar.xz
URL=https://github.com/zen-browser/desktop/releases/latest/download/"$(basename "$DOWNLOAD_PATH")"
if ! tar -tvf "$DOWNLOAD_PATH" &>/dev/null; then
	curl -Lo "$DOWNLOAD_PATH" "$URL"
fi

sudo rm -rf "$INSTALL_PATH"
sudo mkdir -p "$INSTALL_PATH"
sudo tar --strip-components=1 -C "$INSTALL_PATH" -xvf "$DOWNLOAD_PATH"
sudo chown -R "$USER" "$INSTALL_PATH"

tee "$HOME"/.local/bin/zen <<-EOF
	#/usr/bin/env bash
	exec $INSTALL_PATH/zen \${@}
EOF
chmod +x "$HOME"/.local/bin/zen

mkdir -p "$HOME"/.local/share/applications
tee "$HOME"/.local/share/applications/zen.desktop <<-EOF
	[Desktop Entry]
	Name=Zen Browser
	Comment=Experience tranquillity while browsing the web without people tracking you!
	Keywords=web;browser;internet
	Exec=$INSTALL_PATH/zen %u
	Icon=$INSTALL_PATH/browser/chrome/icons/default/default128.png
	Terminal=false
	StartupNotify=true
	StartupWMClass=zen
	NoDisplay=false
	Type=Application
	MimeType=text/html;text/xml;application/xhtml+xml;application/vnd.mozilla.xul+xml;text/mml;x-scheme-handler/http;x-scheme-handler/https;
	Categories=Network;WebBrowser;
	Actions=new-window;new-private-window;profile-manager-window;
	[Desktop Action new-window]
	Name=Open a New Window
	Exec=$INSTALL_PATH/zen --new-window %u
	[Desktop Action new-private-window]
	Name=Open a New Private Window
	Exec=$INSTALL_PATH/zen --private-window %u
	[Desktop Action profile-manager-window]
	Name=Open the Profile Manager
	Exec=$INSTALL_PATH/zen --ProfileManager
EOF
